apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      nodeSelector:
        workload: app

      containers:
        - name: frontend

          image: omkar1907/mern-frontend:v11

          imagePullPolicy: Always

          ports:
            - containerPort: 80 