server:
  nodeSelector:
    role: monitoring
  tolerations:
    - key: dedicated
      operator: Equal
      value: monitoring
      effect: NoSchedule
  extraArgs:
    - --rootpath=/argocd
    - --insecure

repoServer:
  nodeSelector:
    role: monitoring
  tolerations:
    - key: dedicated
      operator: Equal
      value: monitoring
      effect: NoSchedule

controller:
  nodeSelector:
    role: monitoring
  tolerations:
    - key: dedicated
      operator: Equal
      value: monitoring
      effect: NoSchedule

applicationSet:
  nodeSelector:
    role: monitoring
  tolerations:
    - key: dedicated
      operator: Equal
      value: monitoring
      effect: NoSchedule